local-simulation:
  user-workflow:
    workflow-name: "aura-nav-por-workflow"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../secrets.yaml"

staging:
  user-workflow:
    workflow-name: "aura-nav-por-workflow"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../secrets.yaml"
